version: "3.8"
services:
    mosquitto:
        container_name: mosquitto_MQTT
        build: ./builds/mosquitto
        ports:
          - "1883:1883"
        volumes:
          - ./volumes/mosquitto/config:/mosquitto/config
          - ./volumes/mosquitto/data:/mosquitto/data
          - ./volumes/mosquitto/log:/mosquitto/log
        environment:
            MOSQUITTO_USERNAME: demo
            MOSQUITTO_PASSWORD: 1234
            TZ: Asia/Bangkok
        restart: always

    influxdb:
        container_name: influxdb
        image: influxdb:1.8.3
        ports:
          - "8086:8086"
        volumes:
          - ./volumes/influxdb:/var/lib/influxdb
        environment:
            PRE_CREATE_DB: IoTDevice
            INFLUXDB_ADMIN_ENABLED: "true"
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: 123456
            INFLUXDB_USER: user
            INFLUXDB_USER_PASSWORD: 123456
            INFLUXDB_DB: IoTDevice
            TZ: Asia/Bangkok
        restart: always
    
    
