version: "3.8"
services:
    mosquitto:
        container_name: mosquitto_MQTT
        build: ./builds/mosquitto
        ports:
          - "1883:1883"
        volumes:
          - ./volumes/mosquitto/config:/mosquitto/config
          - ./volumes/mosquitto/data:/mosquitto/data
          - ./volumes/mosquitto/log:/mosquitto/log
        environment:
            MOSQUITTO_USERNAME: demo
            MOSQUITTO_PASSWORD: 1234
            TZ: Asia/Bangkok
        restart: always

    influxdb:
        container_name: influxdb
        image: influxdb:1.8.3
        ports:
          - "8086:8086"
        volumes:
          - ./builds/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
          - ./volumes/influxdb:/var/lib/influxdb
        environment:
            INFLUXDB_DB: IoTDevice
            INFLUXDB_HTTP_AUTH_ENABLED: "true"
            INFLUXDB_ADMIN_ENABLED: "true"
            INFLUXDB_ADMIN_USER: admin
            INFLUXDB_ADMIN_PASSWORD: 123456
            INFLUXDB_USER: user
            INFLUXDB_USER_PASSWORD: 123456
            TZ: Asia/Bangkok

            # INFLUXDB_READ_USER: 
            # INFLUXDB_READ_USER_PASSWORD:
            # INFLUXDB_WRITE_USER:
            # INFLUXDB_WRITE_USER_PASSWORD:
        restart: always

    telegraf:
        container_name: telegraf
        image: telegraf:1.15.3
        depends_on:
            - influxdb
        volumes:
            - ./builds/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
        environment:
            TZ: Asia/Bangkok
        restart: always

    platform:
        container_name: portainer
        image: portainer/portainer
        ports:
          - 9000:9000
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock
        environment:
          TZ: Asia/Bangkok
        restart: always

networks:
    default:
        external:
            name: IoT-Site